FROM quay.io/openshift-psap-qe/ubi9-minimal
#RUN rpm install -y \
#https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
RUN microdnf install -y \
    nc iputils dnf subscription-manager\
    && dnf clean all
RUN dnf install -y \
https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
RUN subscription-manager register --username xxxxx --password xxxxx
RUN dnf install -y \
    tcpdump\
    && dnf clean all
