apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 01-worker-ovsdb-cpu-affinity
spec:
  config:
    ignition:
      version: 3.4.0 
    storage:
      files:
        - path: /etc/systemd/system/ovsdb-server.service.d/cpu-affinity.conf
          mode: 0644 
          overwrite: true
          contents:
            source: data:text/plain;charset=utf-8;base64,W1NlcnZpY2VdCkNQVUFmZmluaXR5PTIgMwo=
